version: '3.4'

services:
    producer:
        environment:
            - DOTNET_ENVIRONMENT=Development
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    consumer:
        environment:
            - DOTNET_ENVIRONMENT=Development
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
